[default]
TITLE="Controle Financeiro"

SQLALCHEMY_DATABASE_URI="sqlite:///db.sqlite"
SQLALCHEMY_TRACK_MODIFICATIONS = false


EXTENSIONS = [
    "app.ext.flask_sqlalchemy:init_app",
    "app.ext.flask_migrate:init_app",

    "app.blueprints.api:init_app"
]

[production]